service: api-wedding

custom:
  secrets: ${file(secrets.json)}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

functions:
  guest_register_batch:
    handler: guests/handler.createBatch
    events:
      - http:
          path: guests/batch
          method: post
          cors: true
  guest_register:
    handler: guests/handler.create
    events:
      - http:
          path: guests
          method: post  
          cors: true
  guest_delete:
    handler: guests/handler.delete
    events:
      - http:
          path: guests/{id}
          method: delete  
          cors: true      
  guest_update:
    handler: guests/handler.update
    events:
      - http:
          path: guests
          method: patch
          cors: true
  guest_list:
    handler: guests/handler.list
    events:
      - http:
          path: guests
          method: get
          cors: true
  guest_list_all:
    handler: guests/handler.listAll
    events:
      - http:
          path: guests/all
          method: get
          cors: true
  wall_messages_register:
    handler: wall-messages/handler.create
    events:
      - http:
          path: wall-messages
          method: post
          cors: true
  wall_messages_delete:
    handler: wall-messages/handler.delete
    events:
      - http:
          path: wall-messages
          method: delete
          cors: true
  wall_messages_update:
    handler: wall-messages/handler.update
    events:
      - http:
          path: wall-messages/{id}
          method: patch
          cors: true    
  wall_message_list:
    handler: wall-messages/handler.list
    events:
      - http:
          path: wall-messages
          method: get
          cors: true
  wall_message_list_all:
    handler: wall-messages/handler.listAll
    events:
      - http:
          path: wall-messages/all
          method: get
          cors: true
  wall_message_get:
    handler: wall-messages/handler.get
    events:
      - http:
          path: wall-messages/{id}
          method: get
          cors: true
  wall_message_delete:
    handler: wall-messages/handler.delete
    events:
      - http:
          path: wall-messages/{id}
          method: delete
          cors: true
  wished_musics_register:
    handler: wished-musics/handler.create
    events:
      - http:
          path: wished-musics
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  wished_musics_list:
    handler: wished-musics/handler.list
    events:
      - http:
          path: wished-musics
          method: get
          cors: true      
  ranking_list:
    handler: wished-musics/handler.ranking
    events:
      - http:
          path: ranking
          method: get
          cors: true
  ranking_all:
    handler: wished-musics/handler.rankingAll
    events:
      - http:
          path: ranking/all
          method: get
          cors: true